import { useEffect, useState } from 'react'
import { answerReassessment, getLearner, getQuestion, makeIntervention, startReassessment, submitAnswer } from './services/api'
import type { Assessment, Diagnosis, Intervention, Learner, Question } from './types'

type Step = 'dashboard' | 'learn' | 'intervention' | 'reassess' | 'progress'
const steps: {id: Step; label: string; icon: string}[] = [
  {id:'dashboard', label:'Today', icon:'grid-1x2'}, {id:'learn', label:'Practice', icon:'pencil-square'}, {id:'progress', label:'Progress', icon:'graph-up-arrow'}
]

export default function App() {
  const [step, setStep] = useState<Step>('dashboard')
  const [question, setQuestion] = useState<Question | null>(null)
  const [learner, setLearner] = useState<Learner | null>(null)
  const [answer, setAnswer] = useState('')
  const [reasoning, setReasoning] = useState('')
  const [submissionId, setSubmissionId] = useState<number | null>(null)
  const [diagnosis, setDiagnosis] = useState<Diagnosis | null>(null)
  const [intervention, setIntervention] = useState<Intervention | null>(null)
  const [assessment, setAssessment] = useState<Assessment | null>(null)
  const [followupAnswer, setFollowupAnswer] = useState('')
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const refresh = async () => { const [q, p] = await Promise.all([getQuestion(), getLearner()]); setQuestion(q); setLearner(p) }
  useEffect(() => { refresh().catch(e => setError(e.message)) }, [])
  const run = async (work: () => Promise<void>) => { setBusy(true); setError(''); try { await work() } catch (e) { setError(e instanceof Error ? e.message : 'Please try again.') } finally { setBusy(false) } }
  const submit = () => run(async () => { if (!question || !answer.trim()) return; const result = await submitAnswer(question.id, answer, reasoning); setSubmissionId(result.id); setDiagnosis(result.diagnosis); if (result.diagnosis.needs_intervention) setStep('intervention'); else { await refresh() } })
  const openIntervention = () => run(async () => { if (!submissionId) return; setIntervention(await makeIntervention(submissionId)) })
  const beginAssessment = () => run(async () => { if (!intervention) return; setAssessment(await startReassessment(intervention.id)); setStep('reassess') })
  const submitFollowUp = () => run(async () => { if (!intervention || !assessment || !followupAnswer.trim()) return; const r = await answerReassessment(intervention.id, assessment.assessment_id, followupAnswer); setAssessment(r); await refresh() })
  const nav = (target: Step) => { setStep(target); if (target === 'learn') { setAnswer(''); setReasoning(''); setDiagnosis(null) } }
  if (error) return <main className="error-shell"><h1>Re:Learn</h1><p>{error}</p><button className="btn btn-primary" onClick={() => refresh().catch(e => setError(e.message))}>Try again</button></main>
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">R</span><span>Re:Learn</span></div><p className="eyebrow">YOUR LEARNING SPACE</p>{steps.map(item => <button key={item.id} className={`nav-link ${step === item.id ? 'active' : ''}`} onClick={() => nav(item.id)}><i className={`bi bi-${item.icon}`}/>{item.label}</button>)}<div className="sidebar-foot"><div className="avatar">AL</div><div><strong>Alex Learner</strong><small>Python foundations</small></div></div></aside><main className="content"><header><div><p className="eyebrow">ADAPTIVE PRACTICE</p><h1>{step === 'dashboard' ? 'Good afternoon, Alex.' : step === 'learn' ? 'Let’s think it through.' : step === 'intervention' ? 'A focused reset.' : step === 'reassess' ? 'Try it in a new setting.' : 'Your learning story.'}</h1></div><span className="streak"><i className="bi bi-lightning-charge-fill"/> 3 day streak</span></header>
  {step === 'dashboard' && <Dashboard learner={learner} onPractice={() => nav('learn')} />}
  {step === 'learn' && question && <section className="practice-card"><div className="card-top"><span className="pill">Python · Beginner</span><span>01 / 01</span></div><p className="prompt-label">YOUR QUESTION</p><pre className="question-code">{question.prompt}</pre><label>Your answer</label><textarea value={answer} onChange={e => setAnswer(e.target.value)} placeholder="For example: 1 2 3 4" rows={2}/><details><summary>Add your reasoning (optional)</summary><textarea value={reasoning} onChange={e => setReasoning(e.target.value)} placeholder="What made you choose that answer?" rows={2}/></details>{diagnosis && !diagnosis.needs_intervention && <div className={`feedback ${diagnosis.is_correct ? 'success' : 'neutral'}`}><i className={`bi bi-${diagnosis.is_correct ? 'check-circle-fill' : 'info-circle-fill'}`}/><div><strong>{diagnosis.is_correct ? 'Exactly right.' : 'Let’s pause before labeling this.'}</strong><p>{diagnosis.evidence[0]}</p></div></div>}<button disabled={busy || !answer.trim()} className="btn btn-dark submit" onClick={submit}>{busy ? 'Checking…' : 'Check my thinking'} <i className="bi bi-arrow-right"/></button></section>}
  {step === 'intervention' && diagnosis && <section className="intervention"><div className="diagnosis-banner"><div className="round-icon"><i className="bi bi-compass"/></div><div><span className="pill coral">Pattern noticed</span><h2>You may be counting the stop value, too.</h2><p>{diagnosis.evidence[0]}</p></div></div>{!intervention ? <button className="btn btn-dark submit" disabled={busy} onClick={openIntervention}>Show me a focused explanation <i className="bi bi-arrow-right"/></button> : <><div className="lesson-grid"><article><p className="eyebrow">WHY THIS HAPPENS</p><h3>{intervention.title}</h3><p>{intervention.explanation}</p></article><article className="example"><p className="eyebrow">TRACE IT</p><p>{intervention.worked_example}</p></article></div><div className="hint"><i className="bi bi-lightbulb-fill"/><div><strong>Try this first</strong><p>{intervention.guided_hint}</p></div></div><button className="btn btn-dark submit" disabled={busy} onClick={beginAssessment}>I’m ready for a new example <i className="bi bi-arrow-right"/></button></>}</section>}
  {step === 'reassess' && assessment && <section className="practice-card reassess"><span className="pill mint">Same idea, different example</span><p className="prompt-label">FOLLOW-UP QUESTION</p><pre className="question-code">{assessment.question.prompt}</pre><label>Your answer</label><textarea value={followupAnswer} disabled={assessment.status !== 'pending'} onChange={e => setFollowupAnswer(e.target.value)} placeholder="Write the output values" rows={2}/>{assessment.status !== 'pending' && <div className={`feedback ${assessment.status === 'resolved' ? 'success' : 'neutral'}`}><i className={`bi bi-${assessment.status === 'resolved' ? 'check-circle-fill' : 'arrow-repeat'}`}/><div><strong>{assessment.status === 'resolved' ? 'You carried the idea into a new problem.' : 'This pattern may need one more pass.'}</strong><p>{assessment.evidence[0]}</p></div></div>}{assessment.status === 'pending' ? <button disabled={busy || !followupAnswer.trim()} className="btn btn-dark submit" onClick={submitFollowUp}>{busy ? 'Checking…' : 'Check this answer'} <i className="bi bi-arrow-right"/></button> : <button className="btn btn-outline-dark submit" onClick={() => nav('progress')}>See my progress</button>}</section>}
  {step === 'progress' && <Progress learner={learner} onPractice={() => nav('learn')} />}</main></div>
}

function Dashboard({learner, onPractice}: {learner: Learner | null; onPractice: () => void}) { const mastery = Math.round((learner?.mastery.C001 ?? .35) * 100); return <><section className="hero"><div><span className="pill mint">ONE FOCUSED PRACTICE</span><h2>Build confidence with<br/>loop boundaries.</h2><p>Small practice, clear feedback, and a check that the idea really sticks.</p><button className="btn btn-dark" onClick={onPractice}>Start practice <i className="bi bi-arrow-right"/></button></div><div className="hero-orbit"><div className="orbit-core">{mastery}<small>%</small><span>confidence</span></div><i className="bi bi-braces-asterisk"/></div></section><section className="stat-row"><div><small>CURRENT CONCEPT</small><strong>Python loops</strong><span>{mastery}% confidence</span></div><div><small>ACTIVE FOCUS</small><strong>{learner?.active_misconceptions.length ? 'Loop boundaries' : 'Ready for practice'}</strong><span>One idea at a time</span></div><div><small>RECENT WINS</small><strong>{learner?.resolved_misconceptions.length || 0} resolved</strong><span>Understanding that transfers</span></div></section><section className="activity"><div><h3>Your path today</h3><span className="muted">A complete learning loop</span></div><div className="path"><span className="path-done"><i className="bi bi-1-circle-fill"/> Notice</span><i className="bi bi-arrow-right"/><span><i className="bi bi-2-circle"/> Practice</span><i className="bi bi-arrow-right"/><span><i className="bi bi-3-circle"/> Check again</span></div></section></> }
function Progress({learner, onPractice}: {learner: Learner | null; onPractice: () => void}) { const mastery = Math.round((learner?.mastery.C001 ?? .35) * 100); return <section className="progress-page"><div className="progress-card"><p className="eyebrow">PYTHON LOOP BOUNDARIES</p><h2>{mastery}% confidence</h2><div className="progress"><div className="progress-bar" style={{width:`${mastery}%`}}/></div><p>You’re building understanding through explanation and transfer, not just answer streaks.</p></div><div className="history"><h3>Recent learning activity</h3>{learner?.trajectory.length ? learner.trajectory.slice().reverse().map((x,i) => <div className="history-row" key={i}><span className={x.status === 'resolved' ? 'dot good' : 'dot'}/><div><strong>{x.status === 'resolved' ? 'Boundary understanding generalized' : 'Boundary pattern identified'}</strong><p>{x.evidence[0]}</p></div></div>) : <p className="muted">Start a practice to create your learning record.</p>}</div><button className="btn btn-dark" onClick={onPractice}>Practice again <i className="bi bi-arrow-right"/></button></section> }
